In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\PARIMAL\OneDrive\Desktop\Data Science Internship\Projects\Finance_Project\Finance_Project\insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
df.duplicated().sum()

np.int64(1)

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [7]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1337 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   object
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   object
 5   region    1337 non-null   object
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 83.6+ KB

In [9]:
unq_sex = df['sex'].unique()
unq_sex

dict_sex = {
        'female':1, 
        'male':2
}
df['sex'] = df['sex'].map(dict_sex)

In [10]:
unq_region = df['region'].unique()
unq_region

dict_region = {
    'southwest':1, 'southeast':2, 'northwest':3, 'northeast':4
}
df['region'] = df['region'].map(dict_region)

In [11]:
unq_smoker = df['smoker'].unique()
unq_smoker

dict_smoker = {
    'yes':1, 'no':2
}

df['smoker'] = df['smoker'].map(dict_smoker)

In [12]:
df

      age  sex     bmi  children  smoker  region      charges
0      19    1  27.900         0       1       1  16884.92400
1      18    2  33.770         1       2       2   1725.55230
2      28    2  33.000         3       2       2   4449.46200
3      33    2  22.705         0       2       3  21984.47061
4      32    2  28.880         0       2       3   3866.85520
...   ...  ...     ...       ...     ...     ...          ...
1333   50    2  30.970         3       2       3  10600.54830
1334   18    1  31.920         0       2       4   2205.98080
1335   18    1  36.850         0       2       2   1629.83350
1336   21    1  25.800         0       2       1   2007.94500
1337   61    1  29.070         0       1       3  29141.36030

[1337 rows x 7 columns]

In [13]:
x = df.drop(['charges'],axis=1) # independent Variable (Input)
y = df['charges']

In [14]:
x

      age  sex     bmi  children  smoker  region
0      19    1  27.900         0       1       1
1      18    2  33.770         1       2       2
2      28    2  33.000         3       2       2
3      33    2  22.705         0       2       3
4      32    2  28.880         0       2       3
...   ...  ...     ...       ...     ...     ...
1333   50    2  30.970         3       2       3
1334   18    1  31.920         0       2       4
1335   18    1  36.850         0       2       2
1336   21    1  25.800         0       2       1
1337   61    1  29.070         0       1       3

[1337 rows x 6 columns]

In [15]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1337, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [106]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, random_state=42)

model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [107]:
print("The Train Score Is: ",model.score(x_train,y_train))
print("The Test Score Is: ",model.score(x_test,y_test))

The Train Score Is:  0.9736837535934051
The Test Score Is:  0.8808271641009859

In [108]:
y_pred = model.predict(x_test)
y_pred

array([10309.155615 ,  6117.3995133, 12425.3745526, 41959.1386424,
        5793.0906476, 10175.0222939, 38447.4486648,  2098.438796 ,
        7900.4971723, 10432.6856785, 14524.405127 , 23849.2530672,
       42456.7472082, 15350.271642 ,  6980.2622197,  8732.2804828,
        7047.8923905, 39541.1618852,  4188.0022594,  4985.0530344,
        3683.2085528, 21092.9163499,  9848.4529126, 20429.7335829,
       38328.4068728, 17817.4556455, 43189.6723222, 45816.8603455,
       10953.721798 , 15843.5314022,  4401.2613083,  9574.5030838,
        2061.8697971, 14676.9632177, 47316.2164902,  9772.4758151,
        7584.1957544,  5147.882731 , 22864.9840341,  9553.2199589,
        3165.281708 , 21224.2555634, 41742.9968077,  9661.8432109,
        9124.3173066,  3424.0477548,  3424.337889 ,  7832.7032847,
        6340.5438025, 12182.6923096,  4725.5357101, 11008.7982049,
       23098.5587814,  5776.221544 ,  7181.124535 ,  8328.076133 ,
       11287.7667003,  5924.0573825, 41327.5153296,  7412.846401 ,
       10926.2569051,  5790.4276844, 18877.3755584,  1735.9252875,
       14085.4304994, 14720.9156314,  7857.9060574, 22899.4656414,
       16890.8519733, 17662.2286458, 13831.6467308, 15808.587725 ,
        7988.6996546,  7003.934018 , 11510.6451639,  3711.769062 ,
       14153.8232467,  5459.8463985, 10951.7142836, 12778.246231 ,
       10175.588062 , 18406.9899213, 14270.4426644,  8419.850473 ,
       28697.735962 , 15450.4241455,  3856.8304522,  2042.0290399,
        6413.307457 ,  3856.7593765, 15680.8217597, 17774.2659875,
        7096.6342671,  8880.7855902,  1764.0082565, 43903.629252 ,
       12686.8727624, 10155.8678946,  5368.1611292,  9480.7259462,
       13736.814351 , 16142.0880585, 23944.9713682, 15806.2852499,
       40867.7276238,  1630.22124  , 41287.4851992, 18655.3652568,
       12796.4942823,  6382.3335185,  7052.8238842, 12483.7360164,
        7028.5481472,  7238.4536559,  2225.1687636,  2158.9586585,
        3596.6472627,  4671.0111479,  2511.1183411, 13680.5410912,
       44087.4161515,  5918.9323954,  7605.5025484,  6383.0659007,
        8056.9711137,  7766.6674883,  5635.3028003, 13879.5748068,
       38999.0984928, 48405.0302001, 28585.1835725,  9975.3812069,
        2400.347768 , 11845.1486031,  6075.1776779, 11956.5273078,
       46198.987265 , 22409.0751622, 18848.5435783,  4040.7621482,
        6396.8034863, 11080.2449265, 43598.7168656, 11934.0930723,
        1445.4495125,  5790.4776925,  5958.341163 ,  7993.8814567,
       43011.3217912, 13574.0210535,  6699.5391603,  9094.3709057,
        6009.7277551, 14348.1763595,  8364.3923022, 35908.53876  ,
       43296.584239 , 11286.5949453,  9684.319815 ,  9744.344459 ,
       11657.8403211,  6629.1200878, 11859.0628271, 12160.667626 ,
       44037.851715 , 40483.789837 , 11254.4481105, 19178.1125179,
        6067.7512015,  4547.0981374,  5041.5939192,  2015.311441 ,
        4080.7974442, 15496.1707917,  9118.8119206, 17061.660012 ,
        2581.8609934,  9839.6109249,  9910.9975966, 10437.8821202,
       15879.1458179,  4405.2394844, 13879.4412078, 14137.0904378,
       39867.4967173, 11593.4001201,  5091.2848045,  5345.1469584,
        2093.333154 , 45016.6453995,  3441.7494413, 23361.5921545,
       14424.0455392,  5731.098713 ,  2707.483259 ,  8577.8701226,
       39335.326388 ,  4658.9520159, 14857.5878102, 17620.4643516,
       34425.7600165, 18788.4145638,  4924.674842 , 10819.2532842,
       19076.339368 ,  6872.6535556,  7484.511341 ,  8352.8092734,
        6716.2862065, 42082.3124267, 23831.0150214,  9741.7678525,
        4961.5205903,  7321.5036603, 14742.9204362,  1783.5550615,
        2137.417946 ,  8729.4028622, 11266.3871968,  8145.8239896,
        3170.9995189, 45037.6783205, 45447.9763216, 21352.5054955,
        9882.3707321, 46680.3185205, 41604.2255905, 11172.7213556,
       35646.2138995,  8819.8003738, 13226.2827075, 38116.7143582,
        6315.4030598,  7100.8766605, 12731.159487 , 14980.7649944,
       13708.664597 ,  1821.0695395,  3211.8572622,  4128.4108867,
        5646.6599923,  3293.7360919,  6675.5116669, 11103.1731549,
        1646.0787425, 10072.3477443,  6389.2182643,  8274.4700916,
        4362.8006179,  9405.2479484,  6216.6109262, 11751.4429309,
       12583.5775895, 14449.2267475, 44529.5657505, 13885.4416535,
       13966.2160786,  8289.1525847,  7774.0984328, 10817.8471645,
       37185.3922777, 46795.076925 , 16101.0960226, 14263.4769254,
       14480.6668526, 12722.167499 , 47946.718594 , 13034.3693415])

In [109]:
import joblib
joblib.dump(model, 'model.joblib')

['model.joblib']